from pathlib import Path


ROOT = Path("/home/nanda/folder belajar/TA-2026/skripsi_nanda_zip_work")
path = ROOT / "src/01-body/bab4.tex"
text = path.read_text(encoding="utf-8")


replacements = {
    "examples-fft-only": r"""Gambar \ref{fig:examples-fft-only} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi FFT \textit{only}. Dari contoh citra tersebut, sampel citra kelas \f{goldfinch} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu sebesar 0,0006. Sampel ini memiliki nilai \f{mean magnitude} sebesar 5114,49 dan \f{mean phase} sebesar -0,000016. Rendahnya skor probabilitas AI menunjukkan bahwa model memberikan kecenderungan prediksi yang kuat ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra kelas \f{tiger shark} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 0,9994. Sampel ini memiliki nilai \f{mean magnitude} sebesar 532,74 dan \f{mean phase} sebesar 0,000192. Secara visual, citra tersebut tampak memiliki tekstur yang sangat halus dan dominasi warna biru yang tidak menyerupai foto natural. Tingginya skor probabilitas AI diduga berkaitan dengan nilai \f{mean magnitude} yang rendah dan nilai \f{mean phase} yang positif, sehingga model memberikan kecenderungan prediksi yang kuat ke arah kelas \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{goldfish} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9923. Sampel ini memiliki nilai \f{mean magnitude} sebesar 1639,37 dan \f{mean phase} sebesar 0,000303. Secara visual, citra tersebut memiliki objek ikan yang tajam dengan latar belakang yang relatif halus. Nilai \f{mean phase} yang positif dan nilai \f{mean magnitude} yang relatif rendah diduga membuat karakteristik spektral citra ini lebih dekat dengan sebagian citra \f{AI-generated}, sehingga model memberikan prediksi yang keliru.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{koala} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang rendah, yaitu sebesar 0,0264. Sampel ini memiliki nilai \f{mean magnitude} sebesar 3011,10 dan \f{mean phase} sebesar -0,000000. Secara visual, citra tersebut masih tampak menyerupai foto natural karena objek koala dan latar dedaunan terlihat cukup realistis. Rendahnya skor probabilitas AI diduga berkaitan dengan nilai \f{mean phase} yang sangat dekat dengan nol, sehingga model memberikan kecenderungan prediksi ke arah kelas \f{nature}.""",

    "examples-clip-only": r"""Gambar \ref{fig:examples-clip-only} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi CLIP \textit{only}. Dari contoh citra tersebut, sampel citra kelas \f{golden retriever} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu mendekati 0,0000. Pada ruang t-SNE fitur CLIP, sampel ini memiliki nilai t-SNE 1 sebesar -20,19 dan t-SNE 2 sebesar 27,85. Secara visual, citra tersebut memperlihatkan objek anjing dengan tampilan foto natural, sehingga representasi CLIP memberikan kecenderungan prediksi ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{junco} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 1,0000. Sampel ini memiliki nilai t-SNE 1 sebesar 32,90 dan t-SNE 2 sebesar -12,84. Tingginya skor probabilitas AI diduga berkaitan dengan representasi semantik visual citra yang berada pada wilayah fitur yang lebih dekat dengan citra \f{AI-generated}, sehingga model memberikan prediksi yang kuat ke arah kelas \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{golden retriever} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 1,0000. Sampel ini memiliki nilai t-SNE 1 sebesar -30,24 dan t-SNE 2 sebesar 26,28. Walaupun label sebenarnya adalah \f{nature}, representasi CLIP dari citra ini diduga berada pada wilayah yang memiliki kemiripan dengan sebagian citra \f{AI-generated}, sehingga model memberikan prediksi yang keliru.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{Chesapeake Bay retriever} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang sangat rendah, yaitu mendekati 0,0000. Sampel ini memiliki nilai t-SNE 1 sebesar -26,11 dan t-SNE 2 sebesar 24,51. Secara visual, citra tersebut tampak menyerupai foto natural anjing dengan latar yang realistis. Rendahnya skor probabilitas AI diduga berkaitan dengan representasi CLIP yang lebih dekat dengan citra \f{nature}, sehingga model gagal mengenali citra tersebut sebagai citra \f{AI-generated}.""",

    "examples-iqa-only": r"""Gambar \ref{fig:examples-iqa-only} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi IQA \textit{only}. Dari contoh citra tersebut, sampel citra kelas \f{house finch} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang rendah, yaitu sebesar 0,0189. Citra ini memiliki nilai PIQE sebesar 7,89, BRISQUE sebesar 23,74, dan NIQE sebesar 2,89. Rendahnya skor probabilitas AI menunjukkan bahwa berdasarkan fitur kualitas citra, model memberikan kecenderungan prediksi ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{Siamese cat} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9943. Citra ini memiliki nilai PIQE sebesar 79,46, BRISQUE sebesar 52,94, dan NIQE sebesar 5,80. Nilai PIQE dan BRISQUE yang relatif tinggi diduga menunjukkan karakteristik kualitas citra yang berbeda dari sebagian citra \f{nature}, sehingga model memberikan prediksi yang kuat ke arah kelas \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{Chesapeake Bay retriever} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9728. Citra ini memiliki nilai PIQE sebesar 35,00, BRISQUE sebesar 46,64, dan NIQE sebesar 5,25. Nilai BRISQUE dan NIQE yang relatif tinggi diduga membuat karakteristik kualitas citra ini menyerupai sebagian citra \f{AI-generated}, sehingga model memberikan prediksi yang keliru.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{Labrador retriever} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang rendah, yaitu sebesar 0,0516. Citra ini memiliki nilai PIQE sebesar 22,02, BRISQUE sebesar -8,86, dan NIQE sebesar 7,63. Meskipun nilai NIQE cukup tinggi, nilai PIQE dan BRISQUE pada citra ini tidak menunjukkan pola yang cukup kuat untuk mendorong prediksi ke arah kelas \f{AI-generated}. Oleh karena itu, model memberikan kecenderungan prediksi ke arah kelas \f{nature}.""",

    "examples-fft-clip": r"""Gambar \ref{fig:examples-fft-clip} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi FFT + CLIP. Dari contoh citra tersebut, sampel citra kelas \f{stingray} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu sebesar 0,0004. Citra ini memiliki nilai \f{mean magnitude} sebesar 6667,69, \f{mean phase} sebesar -0,000017, t-SNE 1 sebesar -15,55, dan t-SNE 2 sebesar -19,37. Rendahnya skor probabilitas AI menunjukkan bahwa kombinasi fitur spektral dan semantik visual memberikan kecenderungan prediksi yang kuat ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{tabby} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 0,9992. Citra ini memiliki nilai \f{mean magnitude} sebesar 1828,34, \f{mean phase} sebesar 0,000192, t-SNE 1 sebesar -23,92, dan t-SNE 2 sebesar 3,07. Tingginya skor probabilitas AI diduga berkaitan dengan kombinasi nilai fitur spektral dan posisi representasi CLIP yang mendukung prediksi ke arah citra \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{goldfish} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9938. Citra ini memiliki nilai \f{mean magnitude} sebesar 1639,37, \f{mean phase} sebesar 0,000303, t-SNE 1 sebesar -35,89, dan t-SNE 2 sebesar -20,52. Sampel ini merupakan contoh yang juga sulit pada konfigurasi FFT \textit{only}. Hal tersebut menunjukkan bahwa penambahan CLIP belum cukup untuk mengubah kecenderungan prediksi model pada citra ini.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{Siamese cat} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang rendah, yaitu sebesar 0,0131. Citra ini memiliki nilai \f{mean magnitude} sebesar 8550,40, \f{mean phase} sebesar 0,000000, t-SNE 1 sebesar -19,83, dan t-SNE 2 sebesar 11,51. Secara visual, citra tersebut tampak menyerupai foto natural. Rendahnya skor probabilitas AI diduga berkaitan dengan nilai fase yang mendekati nol serta representasi visual yang lebih dekat dengan citra \f{nature}.""",

    "examples-iqa-fft": r"""Gambar \ref{fig:examples-iqa-fft} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi IQA + FFT. Dari contoh citra tersebut, sampel citra kelas \f{goldfinch} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu sebesar 0,0004. Citra ini memiliki nilai \f{mean magnitude} sebesar 5114,49, \f{mean phase} sebesar -0,000016, PIQE sebesar 14,30, BRISQUE sebesar -0,49, dan NIQE sebesar 4,67. Kombinasi nilai fitur tersebut membuat model memberikan kecenderungan prediksi ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{goldfish} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 0,9992. Citra ini memiliki nilai \f{mean magnitude} sebesar 897,49, \f{mean phase} sebesar 0,000383, PIQE sebesar 55,35, BRISQUE sebesar 43,74, dan NIQE sebesar 6,00. Nilai \f{mean magnitude} yang rendah, \f{mean phase} yang positif, serta nilai IQA yang relatif tinggi diduga memperkuat kecenderungan model untuk memprediksi citra sebagai \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{goldfish} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9959. Citra ini memiliki nilai \f{mean magnitude} sebesar 1639,37, \f{mean phase} sebesar 0,000303, PIQE sebesar 49,37, BRISQUE sebesar 35,32, dan NIQE sebesar 5,50. Kedekatan pola fitur spektral dan kualitas citra dengan sebagian citra \f{AI-generated} diduga menyebabkan model memberikan prediksi yang keliru.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{tiger shark} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang rendah, yaitu sebesar 0,0217. Citra ini memiliki nilai \f{mean magnitude} sebesar 5995,80, \f{mean phase} sebesar -0,000000, PIQE sebesar 15,30, BRISQUE sebesar 26,66, dan NIQE sebesar 7,41. Nilai \f{mean phase} yang mendekati nol dan nilai PIQE yang relatif rendah diduga membuat citra ini memiliki karakteristik yang lebih dekat dengan citra \f{nature} pada ruang fitur yang digunakan.""",

    "examples-iqa-clip": r"""Gambar \ref{fig:examples-iqa-clip} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi IQA + CLIP. Dari contoh citra tersebut, sampel citra kelas \f{golden retriever} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu mendekati 0,0000. Citra ini memiliki nilai PIQE sebesar 41,68, BRISQUE sebesar 15,36, NIQE sebesar 4,21, t-SNE 1 sebesar -39,18, dan t-SNE 2 sebesar 26,28. Rendahnya skor probabilitas AI menunjukkan bahwa kombinasi IQA dan CLIP memberikan kecenderungan prediksi yang kuat ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{junco} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 1,0000. Citra ini memiliki nilai PIQE sebesar 65,69, BRISQUE sebesar 45,75, NIQE sebesar 6,53, t-SNE 1 sebesar 25,99, dan t-SNE 2 sebesar -1,16. Nilai IQA yang relatif tinggi dan representasi CLIP pada ruang fitur diduga mendukung prediksi model ke arah kelas \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{Egyptian cat} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 1,0000. Citra ini memiliki nilai PIQE sebesar 24,49, BRISQUE sebesar 16,83, NIQE sebesar 4,27, t-SNE 1 sebesar -19,93, dan t-SNE 2 sebesar -4,09. Kesalahan ini diduga lebih banyak berkaitan dengan representasi semantik visual CLIP, karena nilai IQA pada citra ini tidak tampak ekstrem.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{German short-haired pointer} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang sangat rendah, yaitu mendekati 0,0000. Citra ini memiliki nilai PIQE sebesar 19,57, BRISQUE sebesar -5,46, NIQE sebesar 3,57, t-SNE 1 sebesar -32,51, dan t-SNE 2 sebesar 21,89. Secara visual, citra tersebut tampak cukup realistis. Rendahnya skor probabilitas AI diduga berkaitan dengan nilai IQA yang lebih menyerupai citra natural serta representasi CLIP yang berada dekat dengan wilayah citra \f{nature}.""",

    "examples-iqa-fft-clip": r"""Gambar \ref{fig:examples-iqa-fft-clip} memperlihatkan contoh citra yang diklasifikasikan benar dan salah pada konfigurasi IQA + FFT + CLIP. Dari contoh citra tersebut, sampel citra kelas \f{golden retriever} yang terklasifikasi secara tepat sebagai \f{nature} (\f{true negative}) menunjukkan skor probabilitas AI yang sangat rendah, yaitu sebesar 0,0002. Citra ini memiliki nilai \f{mean magnitude} sebesar 5597,07, \f{mean phase} sebesar 0,000094, PIQE sebesar 29,16, BRISQUE sebesar 18,71, NIQE sebesar 3,38, t-SNE 1 sebesar -26,86, dan t-SNE 2 sebesar 23,59. Kombinasi fitur tersebut membuat model memberikan kecenderungan prediksi yang kuat ke arah kelas \f{nature}.

Kemudian pada sampel citra kedua, yaitu citra \f{AI-generated} kelas \f{tabby} yang terklasifikasi secara tepat sebagai \f{AI-generated} (\f{true positive}), model memberikan skor probabilitas AI yang sangat tinggi, yaitu sebesar 0,9992. Citra ini memiliki nilai \f{mean magnitude} sebesar 1828,34, \f{mean phase} sebesar 0,000192, PIQE sebesar 66,08, BRISQUE sebesar 38,35, NIQE sebesar 5,23, t-SNE 1 sebesar -26,34, dan t-SNE 2 sebesar 6,10. Nilai fitur spektral, kualitas citra, dan representasi visual tersebut secara bersama-sama diduga mendukung prediksi model ke arah kelas \f{AI-generated}.

Kemudian pada sampel citra ketiga, yaitu citra \f{nature} kelas \f{Chihuahua} yang salah diklasifikasikan sebagai \f{AI-generated} (\f{false positive}), model memberikan skor probabilitas AI yang tinggi, yaitu sebesar 0,9884. Citra ini memiliki nilai \f{mean magnitude} sebesar 5081,32, \f{mean phase} sebesar 0,000005, PIQE sebesar 38,50, BRISQUE sebesar 29,75, NIQE sebesar 4,34, t-SNE 1 sebesar -17,09, dan t-SNE 2 sebesar 29,92. Walaupun citra ini merupakan citra \f{nature}, kombinasi fitur pada sampel ini diduga berada dekat dengan sebagian citra \f{AI-generated}, sehingga model memberikan prediksi yang keliru.

Kemudian pada sampel citra keempat, yaitu citra \f{AI-generated} kelas \f{Siamese cat} yang salah diklasifikasikan sebagai \f{nature} (\f{false negative}), model memberikan skor probabilitas AI yang rendah, yaitu sebesar 0,0272. Citra ini memiliki nilai \f{mean magnitude} sebesar 8550,40, \f{mean phase} sebesar 0,000000, PIQE sebesar 18,87, BRISQUE sebesar -0,37, NIQE sebesar 4,81, t-SNE 1 sebesar -14,56, dan t-SNE 2 sebesar 13,55. Secara visual, citra tersebut tampak menyerupai foto natural. Rendahnya skor probabilitas AI diduga berkaitan dengan kombinasi nilai fase yang mendekati nol, nilai PIQE dan BRISQUE yang relatif rendah, serta representasi visual yang tidak cukup kuat mengarah ke kelas \f{AI-generated}.""",
}

for label, new_text in replacements.items():
    old = (
        f"Gambar \\ref{{fig:{label}}} memperlihatkan contoh citra yang diklasifikasikan benar dan salah "
        "pada konfigurasi "
    )
    start = text.find(old)
    if start == -1:
        raise RuntimeError(f"Could not find paragraph start for {label}")
    next_marker_positions = [
        pos for pos in [
            text.find("\n\n\\begin{figure}", start + 1),
            text.find("\n\n\\subsection", start + 1),
            text.find("\n\n\\section", start + 1),
        ]
        if pos != -1
    ]
    end = min(next_marker_positions)
    text = text[:start] + new_text + text[end:]

path.write_text(text, encoding="utf-8")
print(f"Restored detailed example-analysis style in {path}")
